language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)